// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6v-AKSyxRFI3P3RR0GUWWhJqEa2E1WAU',
    appId: '1:306416822440:web:da4564b4971b2db4e9ba9d',
    messagingSenderId: '306416822440',
    projectId: 'snap-e93c7',
    authDomain: 'snap-e93c7.firebaseapp.com',
    storageBucket: 'snap-e93c7.appspot.com',
    measurementId: 'G-EB6XB46C4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBwXehEnbqdktYAor78lemkd4kSFVKAVc',
    appId: '1:306416822440:android:b1b72d4347d9a1bae9ba9d',
    messagingSenderId: '306416822440',
    projectId: 'snap-e93c7',
    storageBucket: 'snap-e93c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtqQHlXjFJIVTtIVKpvLy9d8GA9da40qM',
    appId: '1:306416822440:ios:680293521becaffce9ba9d',
    messagingSenderId: '306416822440',
    projectId: 'snap-e93c7',
    storageBucket: 'snap-e93c7.appspot.com',
    iosBundleId: 'com.example.pr8Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtqQHlXjFJIVTtIVKpvLy9d8GA9da40qM',
    appId: '1:306416822440:ios:680293521becaffce9ba9d',
    messagingSenderId: '306416822440',
    projectId: 'snap-e93c7',
    storageBucket: 'snap-e93c7.appspot.com',
    iosBundleId: 'com.example.pr8Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6v-AKSyxRFI3P3RR0GUWWhJqEa2E1WAU',
    appId: '1:306416822440:web:13fc8a3ef4602442e9ba9d',
    messagingSenderId: '306416822440',
    projectId: 'snap-e93c7',
    authDomain: 'snap-e93c7.firebaseapp.com',
    storageBucket: 'snap-e93c7.appspot.com',
    measurementId: 'G-TTK38FMSF3',
  );
}
